# Configuration file in YAML format

# Dataset settings
NUM_CYCLES: 5
NUM_PREDS: 5
FEATURE_DIM1: 16
FEATURE_DIM2: 16
NUM_ATTENTION: 16

# Training settings
EPOCHS: 2000
LEARNING_RATE: 0.001

# Other settings
BATCH_SIZE: 64
USE_GPU: true