# Configuration file in YAML format

# Dataset settings
NUM_CYCLES: 3
FEATURE_DIM: 16
NUM_ATTENTION: 8

# Training settings
EPOCHS: 2000
LEARNING_RATE: 0.001

# Other settings
BATCH_SIZE: 64
USE_GPU: true