# Configuration file in YAML format

# Dataset settings
NUM_CYCLES: 3
FEATURE_DIM1: 6
FEATURE_DIM2: 6
NUM_ATTENTION: 3

# Training settings
EPOCHS: 2
LEARNING_RATE: 0.001

# Other settings
BATCH_SIZE: 64
USE_GPU: true